theme: jekyll-theme-slate
title: Welcome to Scenty Sensations homepage
description: SCENTY SCENSATIONS IS A NEW FAMILY START UP BUISSNESS SPECIALIZING
IN SCENTED CANDLES ALL SUPPLIED IN A LOVELY JAR FROM ALL SCENTS CREATED,
SCENTED MELTS
